package dvdrental;
// Generated Jun 25, 2021 3:38:36 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bilete generated by hbm2java
 */
public class Bilete  implements java.io.Serializable {


     private int id;
     private int idSpectacol;
     private Date data;
     private int pret;
     private int idVanzare;

    public Bilete() {
    }

    public Bilete(int id, int idSpectacol, Date data, int pret, int idVanzare) {
       this.id = id;
       this.idSpectacol = idSpectacol;
       this.data = data;
       this.pret = pret;
       this.idVanzare = idVanzare;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdSpectacol() {
        return this.idSpectacol;
    }
    
    public void setIdSpectacol(int idSpectacol) {
        this.idSpectacol = idSpectacol;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getPret() {
        return this.pret;
    }
    
    public void setPret(int pret) {
        this.pret = pret;
    }
    public int getIdVanzare() {
        return this.idVanzare;
    }
    
    public void setIdVanzare(int idVanzare) {
        this.idVanzare = idVanzare;
    }




}


