package dvdrental;
// Generated Jun 25, 2021 3:38:36 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Bilete generated by hbm2java
 */
public class Bilet implements java.io.Serializable {

    private Integer id;
    private Date data;
    private int pret;
    private Integer idVanzare;
    private int rand;
    private int loc;
    private Integer locReal;
    private Vanzare vanzare;
    private OraSpectacol oraSpectacol;
    private Integer idOraSpectacol;
    // @ManyToOne
    //  @JoinColumn(name="idSpectacol")
    private Spectacol spectacol;
    private int numarBilet;

    public Integer getIdOraSpectacol() {
        return idOraSpectacol;
    }

    public void setIdOraSpectacol(Integer idOraSpectacol) {
        this.idOraSpectacol = idOraSpectacol;
    }

    public OraSpectacol getOraSpectacol() {
        return oraSpectacol;
    }

    public void setOraSpectacol(OraSpectacol oraSpectacol) {
        this.oraSpectacol = oraSpectacol;
    }

    public int getRand() {
        return rand;
    }

    public void setRand(int rand) {
        this.rand = rand;
    }

    public Integer getLocReal() {
        return locReal;
    }

    public void setLocReal(Integer locReal) {
        this.locReal = locReal;
    }

    public int getLoc() {
        return loc;
    }

    public void setLoc(int loc) {
        this.loc = loc;
    }

    public Bilet() {
    }

    public Bilet(Integer id, Spectacol spectacol, Date data, int pret) {
        this.id = id;
        this.spectacol = spectacol;
        this.data = data;
        this.pret = pret;
       // this.idVanzare = idVanzare;
    }

    public Bilet(Spectacol spectacol, int loc, int rand) {
        this.rand = rand;
        this.loc = loc;
        this.spectacol = spectacol;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public int getPret() {
        return this.pret;
    }

    public void setPret(int pret) {
        this.pret = pret;
    }

    public Spectacol getSpectacol() {
        return spectacol;
    }

    public void setSpectacol(Spectacol spectacol) {
        this.spectacol = spectacol;
    }

    public String getDetalii() {
        return String.format("Bilet: Randul %s, Locul %s", rand + 1, loc);
    }

    public Vanzare getVanzare() {
        return vanzare;
    }

    public void setVanzare(Vanzare vanzare) {
        this.vanzare = vanzare;
    }

    public Integer getIdVanzare() {
        return idVanzare;
    }

    public void setIdVanzare(Integer idVanzare) {
        this.idVanzare = idVanzare;
    }

    public void setNumarBilet(int numarBilet) {
        this.numarBilet = numarBilet;
    }

    public int getNumarBilet() {
        return numarBilet;
    }

    
    
}
