package dvdrental;
// Generated Jun 25, 2021 3:38:36 PM by Hibernate Tools 4.3.1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Spectacole generated by hbm2java
 */
public class Spectacol implements java.io.Serializable, observer.ObserverData {

    private Integer id;
    private String titlu;
    private Date data;
    private int durata;
    private int pret;
    private String tipul;
    private String imagePath;
    private String descriere;

    // @OneToMany(cascade = CascadeType.ALL)
    // @JoinTable(name="spectacolBiletMapping",joinColumns = @JoinColumn(name = "idSpectacol"),inverseJoinColumns = @JoinColumn(name = "idBilet"))
    private Set<Bilet> bilete
            = new HashSet<Bilet>(0);

    public String getTipul() {
        return tipul;
    }

    public void setTipul(String tipul) {
        this.tipul = tipul;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getDescriere() {
        return descriere;
    }

    public void setDescriere(String descriere) {
        this.descriere = descriere;
    }

    public Spectacol() {
    }

    public Spectacol(Integer id, String titlu, Date data, int durata, int pret) {
        this.id = id;
        this.titlu = titlu;
        this.data = data;
        this.durata = durata;
        this.pret = pret;
    }

    public Spectacol(String tipul, String titlu, Date data, String descriere, int pret, int durata) {
        this.titlu = titlu;
        this.data = data;
        this.durata = durata;
        this.pret = pret;
        this.tipul = tipul;
        this.descriere = descriere;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitlu() {
        return this.titlu;
    }

    public void setTitlu(String titlu) {
        this.titlu = titlu;
    }

    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    public int getDurata() {
        return this.durata;
    }

    public void setDurata(int durata) {
        this.durata = durata;
    }

    public int getPret() {
        return this.pret;
    }

    public void setPret(int pret) {
        this.pret = pret;
    }

    public Set<Bilet> getBilete() {
        return bilete;
    }

    public void setBilete(Set<Bilet> bilete) {
        this.bilete = bilete;
    }

    public String getDetalii() {
        DateFormat formatter = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        return String.format("%s %s %s %s", tipul, titlu, formatter.format(data), pret);
    }
}
