package dvdrental;
// Generated Jun 25, 2021 3:38:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vanzari generated by hbm2java
 */
public class Vanzare  implements java.io.Serializable {


     private int id;
     private int idCasier;
     private Date data;
     private int suma;
  private Set<Bilet> bilete
            = new HashSet<Bilet>(0);
    public Vanzare() {
    }

    public  Vanzare(int id, int idCasier, Date data, int suma) {
       this.id = id;
       this.idCasier = idCasier;
       this.data = data;
       this.suma = suma;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdCasier() {
        return this.idCasier;
    }
    
    public void setIdCasier(int idCasier) {
        this.idCasier = idCasier;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getSuma() {
        return this.suma;
    }
    
    public void setSuma(int suma) {
        this.suma = suma;
    }

    public Set<Bilet> getBilete() {
        return bilete;
    }

    public void setBilete(Set<Bilet> bilete) {
        this.bilete = bilete;
    }




}


