/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import org.eclipse.persistence.internal.helper.Helper;

/**
 *
 * @author Stefan
 */
public class FrmAdaugaOre extends javax.swing.JDialog {

    private OnOraSiPretSaved onOraSiPretSaved;

    public FrmAdaugaOre(JDialog owner, boolean modal) {
        super(owner, modal);
        initComponents();
        JSpinner.DateEditor de = new JSpinner.DateEditor(spnOra, "hh:mm");
        spnOra.setEditor(de);

    }

    public FrmAdaugaOre(JDialog owner, boolean modal, String dataCurenta, int pretCurent) throws ParseException {
        super(owner, modal);

        initComponents();

        Date date1 = new SimpleDateFormat("hh:mm").parse(dataCurenta);
        spnOra.setValue(date1);
        spnPret.setValue(pretCurent);
        JSpinner.DateEditor de = new JSpinner.DateEditor(spnOra, "hh:mm");
        spnOra.setEditor(de);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOra = new javax.swing.JLabel();
        lblPret = new javax.swing.JLabel();
        spnOra = new javax.swing.JSpinner();
        spnPret = new javax.swing.JSpinner();
        btnSalveaza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblOra.setText("Ora:");

        lblPret.setText("Pret:");

        spnOra.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        btnSalveaza.setText("Salveaza");
        btnSalveaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalveazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnOra, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPret)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnPret, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSalveaza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOra)
                    .addComponent(lblPret)
                    .addComponent(spnOra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalveaza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalveazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalveazaActionPerformed
        onOraSiPretSaved.saveOraSiPret((Date) spnOra.getValue(), (Integer) spnPret.getValue());
        dispose();
    }//GEN-LAST:event_btnSalveazaActionPerformed

    public interface OnOraSiPretSaved {

        void saveOraSiPret(Date ora, int pret);
    }

    public void setOnOraSiPretSaved(OnOraSiPretSaved onOraSiPretSaved) {
        this.onOraSiPretSaved = onOraSiPretSaved;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalveaza;
    private javax.swing.JLabel lblOra;
    private javax.swing.JLabel lblPret;
    private javax.swing.JSpinner spnOra;
    private javax.swing.JSpinner spnPret;
    // End of variables declaration//GEN-END:variables
}
