/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;
import models.Spectacol;
import services.SpectacoleService;
import services.SpectacoleServiceImpl;

/**
 *
 * @author Stefan
 */
public class FrmAddSpectacol extends javax.swing.JDialog {

    private SpectacoleService spectacoleService = new SpectacoleServiceImpl();
    private Spectacol spectacolSelectat;
    private OnSpectacolSaved onSpectacolSaved;

    /**
     * Creates new form FrmAddSpectacol
     */
    
    
    public FrmAddSpectacol(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public FrmAddSpectacol(JDialog parent, boolean modal, Spectacol spectacol) {
        super(parent, modal);
        initComponents();
        this.spectacolSelectat=spectacol;
        txtNumeSpectacol.setText(spectacolSelectat.getTitlu());
        txtDescriere.setText(spectacolSelectat.getDescriere());
        cmbTipSpectacol.setSelectedItem(spectacolSelectat.getTipul());
        jDateChooser1.setDate(spectacolSelectat.getDataOra());
        jSpinner1.setValue(spectacolSelectat.getDataOra());
        spnPret.setValue(spectacolSelectat.getPret());
        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinner1, "HH:mm");
        de.getTextField().setEditable(false);
        jSpinner1.setEditor(de);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeSpectacol = new javax.swing.JLabel();
        txtNumeSpectacol = new javax.swing.JTextField();
        lblTipulSpectacol = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblPret = new javax.swing.JLabel();
        lblOra = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        btnSalvare = new javax.swing.JButton();
        cmbTipSpectacol = new javax.swing.JComboBox<>();
        spnPret = new javax.swing.JSpinner();
        lblDescriereSpectacol = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescriere = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNumeSpectacol.setText("Numele Spectacolului:");

        lblTipulSpectacol.setText("Tipul Spectacolului:");

        lblData.setText("Data:");

        jDateChooser1.setDateFormatString("dd.MM.yyyy");

        lblPret.setText("Pret:");

        lblOra.setText("Ora:");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MINUTE));

        btnSalvare.setText("Salveaza");
        btnSalvare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvareActionPerformed(evt);
            }
        });

        cmbTipSpectacol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Film", "Scena de teatru", "Spectacol" }));

        spnPret.setModel(new javax.swing.SpinnerNumberModel());

        lblDescriereSpectacol.setText("Descriere Spectacol:");

        txtDescriere.setColumns(20);
        txtDescriere.setRows(5);
        jScrollPane1.setViewportView(txtDescriere);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeSpectacol, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescriereSpectacol, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipulSpectacol, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPret, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(spnPret))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblOra)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNumeSpectacol)
                            .addComponent(jScrollPane1)
                            .addComponent(cmbTipSpectacol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvare, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeSpectacol)
                    .addComponent(txtNumeSpectacol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescriereSpectacol)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipSpectacol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipulSpectacol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOra))
                        .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPret))
                .addGap(8, 8, 8)
                .addComponent(btnSalvare)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvareActionPerformed
        String numeSpectacol = txtNumeSpectacol.getText();
        String tipSpectacol = (String) cmbTipSpectacol.getSelectedItem();
        String descriereSpectacol = txtDescriere.getText();
        Date data = jDateChooser1.getDate();
        Date ora = (Date) jSpinner1.getValue();
        Calendar c = Calendar.getInstance();
        Calendar c1 = Calendar.getInstance();
        c1.setTime(ora);
        c.setTime(data);
        c.set(Calendar.HOUR_OF_DAY, c1.get(Calendar.HOUR_OF_DAY));
        c.set(Calendar.MINUTE, c1.get(Calendar.MINUTE));
        Date dataSiOra = c.getTime();
        int pret = (int) spnPret.getValue();
        if (isFormValid()) {
            if (spectacolSelectat == null) {
                spectacolSelectat = new Spectacol(tipSpectacol, numeSpectacol, dataSiOra, descriereSpectacol, pret);
            } else {
                spectacolSelectat.setDescriere(descriereSpectacol);
                spectacolSelectat.setTipul(tipSpectacol);
                spectacolSelectat.setTitlu(numeSpectacol);
                spectacolSelectat.setDataOra(dataSiOra);
                spectacolSelectat.setPret(pret);
            }
            onSpectacolSaved.saveSpectacol(spectacolSelectat);
            spectacoleService.salveazaSpectacol(spectacolSelectat);
            JOptionPane.showMessageDialog(this, "Spectacolul a fost salvat cu succes!");
            dispose(); 
        }

    }//GEN-LAST:event_btnSalvareActionPerformed

    private boolean isFormValid() {
        if (txtNumeSpectacol.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(this, "Numele spectacolului trebuie sa contina minim 3 caractere!");
            txtNumeSpectacol.requestFocusInWindow();
            return false;
        }
        if (txtDescriere.getText().trim().length() < 1) {
            JOptionPane.showMessageDialog(this, "Trebuie sa adaugati o descriere!");
            txtNumeSpectacol.requestFocusInWindow();
            return false;
        }
        if ((int) spnPret.getValue() == 0) {
            JOptionPane.showMessageDialog(this, "Trebuie sa selectati un pret!");
            txtNumeSpectacol.requestFocusInWindow();
            return true;
        }
        return true;
    }

    
    public interface OnSpectacolSaved
    {
        void saveSpectacol(Spectacol s);
    }

    public void setOnSpectacolSaved(OnSpectacolSaved onSpectacolSaved) {
        this.onSpectacolSaved = onSpectacolSaved;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvare;
    private javax.swing.JComboBox<String> cmbTipSpectacol;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescriereSpectacol;
    private javax.swing.JLabel lblNumeSpectacol;
    private javax.swing.JLabel lblOra;
    private javax.swing.JLabel lblPret;
    private javax.swing.JLabel lblTipulSpectacol;
    private javax.swing.JSpinner spnPret;
    private javax.swing.JTextArea txtDescriere;
    private javax.swing.JTextField txtNumeSpectacol;
    // End of variables declaration//GEN-END:variables
}
