/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controllers.CasierController;
import dvdrental.Casier;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import models.CasierB;
import services.CasierService;
import services.CasierServiceImpl;

/**
 *
 * @author Stefan
 */
public class FrmAddCasier extends javax.swing.JDialog {

    private CasierService casierService = new CasierServiceImpl();
    private Casier casierSelectat;
    private OnCasierSaved onCasierSaved;
    private CasierController casierController;

    /**
     * Creates new form FrmAddCasier
     */
    public FrmAddCasier(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public FrmAddCasier(javax.swing.JDialog parent, boolean modal, Casier casier) {
        super(parent, modal);
        initComponents();
        this.casierSelectat = casier;
        txtNume.setText(casier.getNume());
        txtPrenume.setText(casier.getPrenume());
        txtCodOperator.setText(casier.getCodOperator());
    }

    public JTextField getTxtNume() {
        return txtNume;
    }

    public JTextField getTxtPrenume() {
        return txtPrenume;
    }

    public JPasswordField getTxtParola() {
        return txtParola;
    }

    public JTextField getTxtCodOperator() {
        return txtCodOperator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNume = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        lblPrenume = new javax.swing.JLabel();
        txtPrenume = new javax.swing.JTextField();
        lblCodOperator = new javax.swing.JLabel();
        txtCodOperator = new javax.swing.JTextField();
        lblParola = new javax.swing.JLabel();
        txtParola = new javax.swing.JPasswordField();
        btnSalveaza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adauga Casier");

        lblNume.setText("Nume:");

        lblPrenume.setText("Prenume:");

        lblCodOperator.setText("Cod Operator:");

        lblParola.setText("Parola:");

        btnSalveaza.setText("Salveaza");
        btnSalveaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalveazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalveaza))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblParola)
                            .addComponent(lblNume)
                            .addComponent(lblPrenume)
                            .addComponent(lblCodOperator))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrenume, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(txtCodOperator)
                            .addComponent(txtNume)
                            .addComponent(txtParola))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNume)
                    .addComponent(txtNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPrenume)
                    .addComponent(txtPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCodOperator)
                    .addComponent(txtCodOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParola)
                    .addComponent(txtParola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalveaza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalveazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalveazaActionPerformed
        // TODO add your handling code here:
//        String nume = txtNume.getText();
//        String prenume = txtPrenume.getText();
//        String numeComplet = String.format("%s %s", nume, prenume);
//        String codOperator = txtCodOperator.getText();
//        String parola = new String(txtParola.getPassword());
//        if (isFormValid()) {
//            if (casierSelectat == null) {
//                casierSelectat = new Casier(nume, prenume, codOperator, parola);
//            } else {
//               
//                casierSelectat.setCodOperator(codOperator);
//                if (!parola.isEmpty()) {
//                    casierSelectat.setParola(parola);
//                }
//            }
//            casierService.salveazaCasier(casierSelectat);
//            onCasierSaved.saveCasier(casierSelectat);
//            dispose();
//
//        }
        casierController.saveCasier();
    }//GEN-LAST:event_btnSalveazaActionPerformed

    private boolean isFormValid() {
        if (txtNume.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(this, "Numele trebuie sa contina minim 3 caractere!");
            txtNume.requestFocusInWindow();
            return false;
        }
        if (txtPrenume.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(this, "Prenumele trebuie sa aiba minim 3 caractere!");
            txtPrenume.requestFocusInWindow();
            return false;
        }
        if (txtCodOperator.getText().trim().length() < 2) {
            JOptionPane.showMessageDialog(this, "Codul operator trebuie sa aiba minim 2 caractere!");
            txtCodOperator.requestFocusInWindow();
            return false;
        }
        if (casierSelectat != null && txtParola.getPassword().length == 0) {
            return true;
        }
        if (txtParola.getPassword().length < 6) {
            JOptionPane.showMessageDialog(this, "Parola trebuie sa aiba minim 6 caractere!");
            txtParola.requestFocusInWindow();
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddCasier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddCasier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddCasier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddCasier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAddCasier dialog = new FrmAddCasier(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public interface OnCasierSaved {

        void saveCasier(Casier c);
    }

    public void setOnCasierSaved(OnCasierSaved onCasierSaved) {
        this.onCasierSaved = onCasierSaved;
    }

    public void setCasierController(CasierController casierController) {
        this.casierController = casierController;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalveaza;
    private javax.swing.JLabel lblCodOperator;
    private javax.swing.JLabel lblNume;
    private javax.swing.JLabel lblParola;
    private javax.swing.JLabel lblPrenume;
    private javax.swing.JTextField txtCodOperator;
    private javax.swing.JTextField txtNume;
    private javax.swing.JPasswordField txtParola;
    private javax.swing.JTextField txtPrenume;
    // End of variables declaration//GEN-END:variables
}
