/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Date;
import java.util.List;
import javafx.scene.control.Alert;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import models.Bilet;
import services.BiletService;
import services.BiletServiceImpl;

/**
 *
 * @author Stefan
 */
public class FrmListaBilete extends javax.swing.JDialog {

    private List<Bilet> listaBilete;
    private DefaultListModel<Bilet> modelListaBilete=new DefaultListModel<>();
    private BiletService biletService = BiletServiceImpl.getInstance();
    private OnBileteVandute onBileteVandute;
    
    public FrmListaBilete(JDialog parent, boolean modal, List<Bilet> listaBilete) {
        super(parent, modal);
        this.listaBilete=listaBilete;
      
        
        initComponents();
        for (int i=0;i<listaBilete.size();i++){
            modelListaBilete.addElement(listaBilete.get(i));
       }
        System.out.println(modelListaBilete.size());
        jList1.setModel(modelListaBilete);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemBiletListRenderer1 = new renderer.ItemBiletListRenderer();
        itemBiletListRenderer2 = new renderer.ItemBiletListRenderer();
        itemBiletListRenderer3 = new renderer.ItemBiletListRenderer();
        itemBiletListRenderer4 = new renderer.ItemBiletListRenderer();
        itemBiletListRenderer5 = new renderer.ItemBiletListRenderer();
        itemBiletListRenderer6 = new renderer.ItemBiletListRenderer();
        itemBiletListRenderer7 = new renderer.ItemBiletListRenderer();
        itemBiletListRenderer8 = new renderer.ItemBiletListRenderer();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout itemBiletListRenderer1Layout = new javax.swing.GroupLayout(itemBiletListRenderer1);
        itemBiletListRenderer1.setLayout(itemBiletListRenderer1Layout);
        itemBiletListRenderer1Layout.setHorizontalGroup(
            itemBiletListRenderer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        itemBiletListRenderer1Layout.setVerticalGroup(
            itemBiletListRenderer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout itemBiletListRenderer2Layout = new javax.swing.GroupLayout(itemBiletListRenderer2);
        itemBiletListRenderer2.setLayout(itemBiletListRenderer2Layout);
        itemBiletListRenderer2Layout.setHorizontalGroup(
            itemBiletListRenderer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemBiletListRenderer2Layout.setVerticalGroup(
            itemBiletListRenderer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout itemBiletListRenderer3Layout = new javax.swing.GroupLayout(itemBiletListRenderer3);
        itemBiletListRenderer3.setLayout(itemBiletListRenderer3Layout);
        itemBiletListRenderer3Layout.setHorizontalGroup(
            itemBiletListRenderer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemBiletListRenderer3Layout.setVerticalGroup(
            itemBiletListRenderer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout itemBiletListRenderer4Layout = new javax.swing.GroupLayout(itemBiletListRenderer4);
        itemBiletListRenderer4.setLayout(itemBiletListRenderer4Layout);
        itemBiletListRenderer4Layout.setHorizontalGroup(
            itemBiletListRenderer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemBiletListRenderer4Layout.setVerticalGroup(
            itemBiletListRenderer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout itemBiletListRenderer5Layout = new javax.swing.GroupLayout(itemBiletListRenderer5);
        itemBiletListRenderer5.setLayout(itemBiletListRenderer5Layout);
        itemBiletListRenderer5Layout.setHorizontalGroup(
            itemBiletListRenderer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemBiletListRenderer5Layout.setVerticalGroup(
            itemBiletListRenderer5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout itemBiletListRenderer6Layout = new javax.swing.GroupLayout(itemBiletListRenderer6);
        itemBiletListRenderer6.setLayout(itemBiletListRenderer6Layout);
        itemBiletListRenderer6Layout.setHorizontalGroup(
            itemBiletListRenderer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemBiletListRenderer6Layout.setVerticalGroup(
            itemBiletListRenderer6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout itemBiletListRenderer7Layout = new javax.swing.GroupLayout(itemBiletListRenderer7);
        itemBiletListRenderer7.setLayout(itemBiletListRenderer7Layout);
        itemBiletListRenderer7Layout.setHorizontalGroup(
            itemBiletListRenderer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemBiletListRenderer7Layout.setVerticalGroup(
            itemBiletListRenderer7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout itemBiletListRenderer8Layout = new javax.swing.GroupLayout(itemBiletListRenderer8);
        itemBiletListRenderer8.setLayout(itemBiletListRenderer8Layout);
        itemBiletListRenderer8Layout.setHorizontalGroup(
            itemBiletListRenderer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        itemBiletListRenderer8Layout.setVerticalGroup(
            itemBiletListRenderer8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setCellRenderer(itemBiletListRenderer1);
        jList1.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jList1.setVisibleRowCount(1);
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Printeaza si vinde");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (Bilet b:listaBilete){
            b.setDataVanzare(new Date());
            biletService.salveazaBilet(b);
            
        }
        this.setVisible(false);
        JOptionPane.showMessageDialog(this, "Biletele au fost vandute cu succes", "Confirmare vanzare", JOptionPane.INFORMATION_MESSAGE);
        onBileteVandute.saveBilete();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public interface OnBileteVandute {
        void saveBilete ();
    }
    
    public void setOnBileteVandute(OnBileteVandute onBileteVandute){
        this.onBileteVandute=onBileteVandute;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private renderer.ItemBiletListRenderer itemBiletListRenderer1;
    private renderer.ItemBiletListRenderer itemBiletListRenderer2;
    private renderer.ItemBiletListRenderer itemBiletListRenderer3;
    private renderer.ItemBiletListRenderer itemBiletListRenderer4;
    private renderer.ItemBiletListRenderer itemBiletListRenderer5;
    private renderer.ItemBiletListRenderer itemBiletListRenderer6;
    private renderer.ItemBiletListRenderer itemBiletListRenderer7;
    private renderer.ItemBiletListRenderer itemBiletListRenderer8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<Bilet> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
