/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Stefan
 */
public class FrmMeniuPrincipal extends javax.swing.JDialog {

    /**
     * Creates new form FrmMeniuPrincipal
     */
    public FrmMeniuPrincipal(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpectacole = new javax.swing.JTable();
        btnVanzare = new javax.swing.JButton();
        btnSala = new javax.swing.JButton();
        btnDeconecteaza = new javax.swing.JButton();
        btnAdministrare = new javax.swing.JButton();
        btnBilete = new javax.swing.JButton();
        lblAplicatie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblSpectacole.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lista spectacole", "Data si ora", "Bilete ramase", "Bilete vandute"
            }
        ));
        jScrollPane1.setViewportView(tblSpectacole);
        if (tblSpectacole.getColumnModel().getColumnCount() > 0) {
            tblSpectacole.getColumnModel().getColumn(0).setPreferredWidth(110);
            tblSpectacole.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblSpectacole.getColumnModel().getColumn(2).setPreferredWidth(70);
        }

        btnVanzare.setText("Vanzare");

        btnSala.setText("Sala");

        btnDeconecteaza.setText("Deconecteaza-te");

        btnAdministrare.setText("Administrare");

        btnBilete.setText("Bilete");

        lblAplicatie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAplicatie.setForeground(new java.awt.Color(255, 153, 153));
        lblAplicatie.setText("Aplicatie teatru v2.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAplicatie)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdministrare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVanzare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeconecteaza, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnBilete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAplicatie)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVanzare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBilete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdministrare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeconecteaza))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrare;
    private javax.swing.JButton btnBilete;
    private javax.swing.JButton btnDeconecteaza;
    private javax.swing.JButton btnSala;
    private javax.swing.JButton btnVanzare;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAplicatie;
    private javax.swing.JTable tblSpectacole;
    // End of variables declaration//GEN-END:variables
}
