/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Stefan
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spectacolPanel1 = new gui.SpectacolPanel();
        spectacolPanel3 = new gui.SpectacolPanel();
        spectacolPanel5 = new gui.SpectacolPanel();
        spectacolPanel2 = new gui.SpectacolPanel();
        spectacolPanel4 = new gui.SpectacolPanel();
        spectacolPanel6 = new gui.SpectacolPanel();

        setLayout(new java.awt.GridLayout(2, 3, 10, 10));
        add(spectacolPanel1);
        add(spectacolPanel3);
        add(spectacolPanel5);
        add(spectacolPanel2);
        add(spectacolPanel4);
        add(spectacolPanel6);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.SpectacolPanel spectacolPanel1;
    private gui.SpectacolPanel spectacolPanel2;
    private gui.SpectacolPanel spectacolPanel3;
    private gui.SpectacolPanel spectacolPanel4;
    private gui.SpectacolPanel spectacolPanel5;
    private gui.SpectacolPanel spectacolPanel6;
    // End of variables declaration//GEN-END:variables
}
