/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RadialGradientPaint;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.Stroke;
import java.awt.geom.Path2D;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Stefan
 */
public class TicketForm extends javax.swing.JPanel {

    /**
     * Creates new form TicketForm
     */
    public TicketForm() {
        initComponents();
    }

    @Override
    protected void paintComponent(Graphics gr) {
        super.paintComponent(gr);
        Graphics2D g = (Graphics2D) gr;
        
        // Dreptunghi stanga rosu
        g.setColor(new Color(157, 0, 102));
        g.fillRect(0, 0, 75, getHeight());

        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        
        //Fundal
        g.setColor(new Color(234, 213, 188));
        g.fillRect(75, 0, getWidth() - 75, getHeight());
        
        //Chenar
        g.setColor(new Color(157, 0, 102));
        float thickness = 1.5f;
        Stroke oldStroke = g.getStroke();
        g.setStroke(new BasicStroke(thickness));
        g.drawRect(85, 10, getWidth() - 95, getHeight() - 20);
        g.setStroke(oldStroke);
        
        
       // g.setColor(Color.BLACK);
        //g.draw(createDefaultStar(50, 200, 200));
        


        g.setPaint(Color.white);
        g.fill(createStar(35, 33, 5, 11, 5, 90));
        g.fill(createStar(35, 66, 5, 11, 5, 90));
        g.fill(createStar(35, 99, 5, 11, 5, 90));
        g.fill(createStar(35, 132, 5, 11, 5, 90));
        g.fill(createStar(35, 165, 5, 11, 5, 90));
//        g.setPaint(new RadialGradientPaint(
//                new Point(400, 200), 60, new float[]{0, 1},
//                new Color[]{Color.RED, Color.YELLOW}));
       // g.fill(createStar(400, 200, 20, 60, 8, 0));

//        g.setPaint(new RadialGradientPaint(
//                new Point(200, 400), 50, new float[]{0, 0.3f, 1},
//                new Color[]{Color.RED, Color.YELLOW, Color.ORANGE}));
//        g.fill(createStar(200, 400, 40, 50, 20, 0));

    }

    private static Shape createDefaultStar(double radius, double centerX,
            double centerY) {
        return createStar(centerX, centerY, radius, radius * 2.63, 5,
                Math.toRadians(-18));
    }

    private static Shape createStar(double centerX, double centerY,
            double innerRadius, double outerRadius, int numRays,
            double startAngleRad) {
        Path2D path = new Path2D.Double();
        double deltaAngleRad = Math.PI / numRays;
        for (int i = 0; i < numRays * 2; i++) {
            double angleRad = startAngleRad + i * deltaAngleRad;
            double ca = Math.cos(angleRad);
            double sa = Math.sin(angleRad);
            double relX = ca;
            double relY = sa;
            if ((i & 1) == 0) {
                relX *= outerRadius;
                relY *= outerRadius;
            } else {
                relX *= innerRadius;
                relY *= innerRadius;
            }
            if (i == 0) {
                path.moveTo(centerX + relX, centerY + relY);
            } else {
                path.lineTo(centerX + relX, centerY + relY);
            }
        }
        path.closePath();
        return path;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                createAndShowGUI();
            }
        });
    }

    private static void createAndShowGUI() {
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.getContentPane().add(new TicketForm());
        f.setSize(400, 240);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
